### ISSUE TITLE
not working, Gray box returns

### ISSUE THREAD

**Issue by narbelys** [bergben/ng2-img-tools#6] opened 2017-04-21 14:32 UTC
Hello I have a problem with this. 
I put "this.ng2ImgToolsService.compress([file], 2).subscribe" in my code but it return only gray box and I lose the original image. I dont know what is happend. 

Thanks.

**Comment by bergben** [comment] 2017-04-21 17:32
Hey there @narbelys 
Could you please provide the Image you are compressing so that I can reproduce the issue?

**Comment by narbelys** [comment] 2017-04-21 17:58
thanks @bergben 
this is the image 
![20170420_112542](https://cloud.githubusercontent.com/assets/1733675/25290068/a745ccd0-26a2-11e7-8cfe-40188834fc60.jpg)

and this happend with all my image (with size > 2MB)

**Comment by bergben** [comment] 2017-04-21 21:12
I will check it out ASAP, probably in the next 2 days :)

**Comment by bergben** [comment] 2017-04-27 22:35
Sorry for the late answer @narbelys 
I have tried it now and it seems to work fine in my app. I can't reproduce the issue in a plunker either: 
http://plnkr.co/edit/Y8JzvhYPJvcN2CJPhWDk?p=preview

Please try it in the plunker yourself or ideally provide me a plunker that reproduces the issue, thanks! 

Note: The plunkr uses ng2-img-max instead of ng2-img-tools, but ng2-img-max is the library that ng2-img-tools uses to compress images :)

**Comment by narbelys** [comment] 2017-05-02 12:17
Thanks for your answer. 
I'm going to try this :)

**Comment by bergben** [comment] 2017-05-19 21:11
Any news on this? Otherwise I will close this issue.

**Comment by narbelys** [comment] 2017-05-22 13:53
Hi @bergben now this compresses the image perfectly thanks. But I have a question for you, I am trying to process the image and once compressed I can not detect the position through its metadata to be able to put it in the correct position. Does the library do something to this information in the metadata?

Thanks :)

**Comment by bergben** [comment] 2017-05-22 14:57
Hey @narbelys :) What do you mean by position exactly?

**Closed as completed** 2017-06-24 19:48 UTC
